languageCode = 'fr-ca'
title = 'Club Cedille'
theme = 'cedille'


# main menu
[menu]
    [[menu.main]]
        identifier = "accueil"
        name = "Accueil"
        url = "/"
        weight = 1 
    [[menu.main]]
        identifier = "equipe"
        name = "Équipe"
        url = "/equipe/"
        weight = 2
    [[menu.main]]
        identifier = "projets"    
        name = "Projets"
        url = "/projets"
        weight = 3
    [[menu.main]]   
        identifier = "partenaires" 
        name = "Partenaires"
        url = "/partenaires/"
        weight = 4
    [[menu.main]]  
        identifier = "contact" 
        name = "Contact"
        url = "/contact/"
        weight = 5

[params]
    
    titleFollowUs = "Suivez-nous"
    copyright = "©"
    year = "2022"

    #General Params
    [params.general]
    logoCedille = "images/cedille-logo-orange.png"
    
    #Contact Information Params
    [params.address]
    title = "Adresse"
    address = "1219 rue William <br>Montréal (Québec) <br>H3C 1R1 <br>Local D-2020"
    email = "cedille@etsmtl.net"
    phone = "514 396-8800, poste 7302"
    
    #Social Params
    [[params.social]]
    icon = "fab fa-github"
    url = "https://github.com/ClubCedille"
    weight = 1
    [[params.social]]
    icon = "fab fa-facebook-f"
    url = "https://www.facebook.com/clubcedille"
    weight = 2
    [[params.social]]
    icon = "fab fa-instagram"
    url = "https://www.instagram.com/cedille.etsmtl"
    weight = 3
    [[params.social]]
    icon = "fab fa-linkedin-in"
    url = "https://www.linkedin.com/company/cedille/about/"
    weight = 4

