---
name: New Member template
about: This template is used to guide new members to add themselves on the website.
title: As a website visitor, I want to see <member_name> profile on the member page.
labels: ["good first issue"]
assignees: ''
---

### Context / Contexte

The new member's information is not currently displayed on the member page, making it difficult for visitors to know of his belonging to the club and potentially connect with him on professional networks.

*Les informations du nouveau membre ne sont pas encore affichées sur la page des membres, ce qui empêche les visiteurs de connaître son appartenance au club et de se connecter avec lui sur des réseaux professionnels.*

### Acceptance Criteria / Critères d’acceptation

The new member's information is added to the equipe.yml file. This includes:
*Les informations du nouveau membre sont ajoutées au fichier `equipe.yml`. Cela inclut :*

- [ ] Full Name / *Nom complet*  
- [ ] GitHub profile link / *Lien GitHub*  
- [ ] LinkedIn profile link / *Lien LinkedIn*  
- [ ] *(Optional / Optionnel)* Profile picture path (e.g. `images/membres/{nom_image}`) / *Chemin de la photo de profil*

[Optional / Optionnel]  
The profile picture is properly sized to 225x225 pixels.  
*La photo de profil est correctement redimensionnée à 225x225 pixels.*
