name: CI
on: [push, pull_request]

jobs:
  fetchProjects:
    name: Fetch projects information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          name: ClubCedille/tiret     
          ref: refs/heads/release
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: execute py script 
        run: |
          python write_repository.py -o clubcedille -r repo -u user -t pat -y output.yaml # We have to call this for every project.. I think we need all projects in a single file..