name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fetchProjects:
    name: Fetch projects information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Fetch projects informations
        run: make build-projects PAT_TOKEN=${{ secrets.PAT_TOKEN }}  

      - name: Commit and push changes
      
        run: |
          git config --local user.email "cedille@etsmtl.net"
          git config --local user.name "svc-cedille-user"
          git add .
          git commit -m "updating projects yaml files"
      - if : github.ref != 'refs/heads/master'
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch : ${{ github.head_ref }}
          github_token: ${{ secrets.PAT_TOKEN }}
          force: true
      - if : github.ref == 'refs/heads/master'
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch : ${{ github.ref_name }}
          github_token: ${{ secrets.PAT_TOKEN }}
          force: true